//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace Web.Entidades
{

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.33440.
    // 


    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sualud.gob.pe/parserX12/Afiliacion/Online997RegafiUpdateResponse.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sualud.gob.pe/parserX12/Afiliacion/Online997RegafiUpdateResponse.xsd", IsNullable = false)]
    public partial class Online997RegafiUpdateResponse
    {

        private string coErrorField;

        private string txNombreField;

        private string txRespuestaField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coError
        {
            get
            {
                return this.coErrorField;
            }
            set
            {
                this.coErrorField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string txNombre
        {
            get
            {
                return this.txNombreField;
            }
            set
            {
                this.txNombreField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string txRespuesta
        {
            get
            {
                return this.txRespuestaField;
            }
            set
            {
                this.txRespuestaField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sualud.gob.pe/parserX12/Afiliacion/Online997RegafiUpdateResponse.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sualud.gob.pe/parserX12/Afiliacion/Online997RegafiUpdateResponse.xsd", IsNullable = false)]
    public partial class NewDataSet
    {

        private Online997RegafiUpdateResponse[] itemsField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("Online997RegafiUpdateResponse")]
        public Online997RegafiUpdateResponse[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

}